project:
  type: website

website:
  title: "ISS608"
  navbar:
    search: true
    
    left:
      - text: "About FirGhaz"
        href: about.qmd
      - text: "Journey in VAA"
        href: index.qmd
      
    right:
    - text: "Hands-On Exercises"
      menu:
        - text: "Hands-On Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html" 
        - text: "Hands-On Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html" 
        - text: "Hands-On Exercise 3(a)"
          href: "Hands-on_Ex/Hands-on_Ex03(a)/Hands-on_Ex03(a).html" 
        - text: "Hands-On Exercise 3(b)"
          href: "Hands-on_Ex/Hands-on_Ex03(b)/Hands-on_Ex03(b).html"
        - text: "Hands-On Exercise 4(a)"
          href: "Hands-on_Ex/Hands-on_Ex04(a)/Hands-on_Ex04(a).html" 
        - text: "Hands-On Exercise 4(b)"
          href: "Hands-on_Ex/Hands-on_Ex04(b)/Hands-on_Ex04(b).html"
        - text: "Hands-On Exercise 4(c)"
          href: "Hands-on_Ex/Hands-on_Ex04(c)/Hands-on_Ex04(c).html" 
        - text: "Hands-On Exercise 4(d)"
          href: "Hands-on_Ex/Hands-on_Ex04(d)/Hands-on_Ex04(d).html"
        - text: "Hands-On Exercise 5(a)"
          href: "Hands-on_Ex/Hands-on_Ex05(a)/Hands-on_Ex05(a).html" 
        - text: "Hands-On Exercise 5(b)"
          href: "Hands-on_Ex/Hands-on_Ex05(b)/Hands-on_Ex05(b).html"
        - text: "Hands-On Exercise 5(c)"
          href: "Hands-on_Ex/Hands-on_Ex05(c)/Hands-on_Ex05(c).html" 
        - text: "Hands-On Exercise 5(d)"
          href: "Hands-on_Ex/Hands-on_Ex05(d)/Hands-on_Ex05(d).html"
        - text: "Hands-On Exercise 5(e)"
          href: "Hands-on_Ex/Hands-on_Ex05(e)/Hands-on_Ex05(e).html"
    - text: "In-class Exercises"
      menu:
        - text: "In-Class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html" 
        - text: "In-Class Exercise 2"
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html" 
        - text: "In-Class Exercise 3"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html" 
        - text: "In-Class Exercise 4"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html" 
    - text: "Take-Home Exercises"
      menu:
        - text: "Take-Home Exercise 1"
          href: "Take-home_Exercises/Take-Home_Ex01/Take-home_Exercise01.html" 
        - text: "Take-Home Exercise 2"
          href: "Take-home_Exercises/Take-Home_Ex02/Take-home_Exercise02.html" 
        - text: "Take-Home Exercise 3"
          href: "Take-home_Exercises/Take-Home_Ex03/Take-home_Exercise03.html" 
    
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    toc-location: left
    toc-depth: 3
    page-layout: full
    fontsize: 1em
    
editor: visual


          
